NBS:
  num_bones: 1000
  lat_dim: 256

Deform:
  Z_DIM: 256
  decoder_hidden_dim: 256
  decoder_out_dim: 3
  decoder_nlayers: 8

Base:
  Z_DIM: 256
  W_DIM: 256
  IN_CHANNELS: 256
  IMG_CHANNELS: 1
  decoder_lat_dim: 712
  decoder_hidden_dim: 1024
  decoder_nlayers: 8
  decoder_out_dim: 1 

Trainer:
  batch_size: 1
  num_epochs: 1001
  vis_interval:  10
  LR_SW: 0.001
  LR_D: 0.001 # 0.01
  LR_B: 0.05
  epoch_only_shape: -1
  LR_LAT: 0.001
  ckpt_interval: 100
  lr_decay_interval_lat: 200
  lr_decay_factor_lat: 0.5
  START_TRAIN_AT_IMG_SIZE: 8
  shape_checkpoint: checkpoints/baseshape.pth
  save_result: results/IJCV/deform/
  checkpoint_path: checkpoints/IJCV/deform/
  save_name: deform
  grad_clip: 0.025
  grad_clip_lat: 0.025

  lambdas:
    sdf: 1
    sil: 1
    reg_shape: 0.001
    shape: 1
    edge: 1 # 1
    # area: 0.05
    smooth: 1
    normal: 1
    length: 1
    arap: 1
    reg_deform: 0.001
    bone: 10
    map: 0.01

